### ISSUE TITLE
vim.tbl_add_reverse_lookup is deprecated. Feature will be removed in Nvim 0.12

### ISSUE THREAD

**Issue by jiangyinzuo** [sourcegraph/sg.nvim#236] opened 2024-05-17 16:36 UTC
vim.tbl_add_reverse_lookup in NVIM v0.11.0-dev is deprecated.

```
vim.tbl_add_reverse_lookup is deprecated. :help deprecated
Feature will be removed in Nvim 0.12
stack traceback:
        vim/shared.lua: in function 'tbl_add_reverse_lookup'
        /root/plugged/sg.nvim/lua/sg/vendored/vim-lsp-rpc.lua:123: in main chunk
        [C]: in function 'require'
        /root/plugged/sg.nvim/lua/sg/request.lua:2: in main chunk
        [C]: in function 'require'
        /root/plugged/sg.nvim/lua/sg/rpc.lua:4: in main chunk
        [C]: in function 'require'
        /root/plugged/sg.nvim/lua/sg/bufread.lua:4: in main chunk
        [C]: in function 'require'
        /root/plugged/sg.nvim/plugin/sg.lua:7: in main chunk
```

**Comment by marcelarie** [comment] 2024-05-22 09:00
The problem is that it does not have an alternative:

```
LUA
• vim.loop				Use |vim.uv| instead.
• vim.tbl_add_reverse_lookup()
• vim.tbl_flatten()		        Use |Iter:flatten()| instead.
• vim.tbl_islist()			Use |vim.islist()| instead.
```

**Comment by ulisses-cruz** [comment] 2024-05-24 08:52
Thanks to @tjdevries, the deprecation warning was fixed by https://github.com/sourcegraph/sg.nvim/pull/237

**Comment by tjdevries** [comment] 2024-05-24 15:42
Great! Thanks everyone :)

**Closed by tjdevries** 2024-05-24 15:42 UTC
Labels: client/neovim
