### ISSUE TITLE
Support Claude 3 (Cody)

### ISSUE THREAD

**Issue by jmpaz** [sourcegraph/sg.nvim#223] opened 2024-03-15 16:25 UTC
are there plans to support Claude 3 Opus for Cody chat & commands in the near future? just recently subscribed for it / had assumed parity with the recent [vscode release](https://sourcegraph.com/blog/cody-vscode-1-8-0-release).

**Comment by pkos98** [comment] 2024-03-17 05:17
I think Claude 3 is only available for paying Cody users (Pro & Enterprise)

**Comment by manish-baghel** [comment] 2024-03-22 08:56
@jmpaz 
New models support is being added with https://github.com/sourcegraph/sg.nvim/tree/update-cody-agent-03-12 branch.
@tjdevries  is still working on it but I tested on my machine and it works fine so you can checkout to this branch.

If you are using lazy package manager, then you can switch branch something like this,
```lua
{
	"sourcegraph/sg.nvim",
	branch = "update-cody-agent-03-12",
	build = "nvim -l build/init.lua",
....
}
```

**Comment by pkos98** [comment] 2024-03-31 14:05
That was already merged and is ready to use, however only for Pro/Enterprise users.
https://github.com/sourcegraph/sg.nvim/pull/213

I am curious if Claude 3 is only being used for the Chat or also for the code completion?
Because AFAIK there is no completion API available for the Claude 3 models

**Comment by cloud303-cholden** [comment] 2024-04-08 17:24
I can confirm that Claude 3 is working for chat.
![image](https://github.com/sourcegraph/sg.nvim/assets/80974257/455f9dd2-12d2-49aa-8d37-ad425a4f738c)

**Comment by tjdevries** [comment] 2024-05-25 19:00
The models should all be available now (as of a few days ago) and you can set your default chat model with something like this:

```lua
      require("sg").setup {
        accept_tos = true,
        chat = {
          default_model = "opeanai/gpt-4o",
        },
      }
```

**Closed by tjdevries** 2024-05-25 19:00 UTC
Labels: client/neovim
