### ISSUE TITLE
Cody Still not working after updating to the latest version

### ISSUE THREAD

**Issue by Harsh97x** [sourcegraph/sg.nvim#143] opened 2023-10-07 07:07 UTC
After updating to the latest version, Cody still doesn't work and this is the new error that pops up.

```
E5108: Error executing lua: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:136: in function 'callback'
        ...harsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:225: in function 'start'
        ...harsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:213: in function 'chat_question'
        ...rsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/state.lua:84: in function 'request_completion'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:181: in function 'on_submit'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/layout/base.lua:112: in function 'on_submit'
        ...hare/nvim/lazy/sg.nvim/lua/sg/components/cody_prompt.lua:46: in function 'on_submit'
        ...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:78: in function <...are/nvim/lazy/sg.nvim/lua/sg/components/layout/split.lua:77>
```

Also, ran `:checkhealth sg` all the checks showing **OK**

```
sg.nvim report ~
- OK Valid nvim version
- OK Found `cargo` is executable (can still use `:SourcegraphDownloadBinaries` to avoid building locally)
- OK Found `sg-nvim-agent`: "/home/harsh/.local/share/nvim/lazy/sg.nvim/dist/sg-nvim-agent"
- OK Found `node` (config.node_executable) is executable
- OK Found `cody-agent`: /home/harsh/.local/share/nvim/lazy/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables", "nvim", "cody-app" }
- OK   Authentication setup correctly ("nvim")
- OK     endpoint set to: https://sourcegraph.com
- OK sg.nvim is ready to run
```

P.S. I cannot reopen the closed #136 issue, so made a new one. Thanks for looking into it.

**Comment by tjdevries** [comment] 2023-10-08 04:14
When does that error happen?

**Comment by Harsh97x** [comment] 2023-10-08 04:55
[Screencast from 08-10-23 10:20:44 AM IST.webm](https://github.com/sourcegraph/sg.nvim/assets/71343199/80a4f805-8b20-46d0-b4da-77dbe2441577)

**Comment by tjdevries** [comment] 2023-10-09 02:28
Hm, best guess right now is merged with this https://github.com/sourcegraph/sg.nvim/pull/146

(probably needed to be done anyway, so we can see if this fixes the problem at least haha)

**Comment by Harsh97x** [comment] 2023-10-09 02:45
OK, so the good news is that the particular error has disappeared after updating to the latest version. 
The bad news is Cody still doesn't generate anything in response to a prompt.

**Comment by tjdevries** [comment] 2023-10-09 14:24
:laughing: progress is progress i suppose.

Let me update the `:checkhealth` command for sg today to provide some more information so that I can hopefully debug this more effectively (for you and other people haha)

Thanks for the patience.

Does the auto-complete work at all for you?

Also, could you try re-generating your access token maybe as well. Just in case there is something goofy about the token. I'll try and add a bit more info about that and maybe double-check that the auth validation is working

**Comment by Harsh97x** [comment] 2023-10-09 15:21
Yeah, we are getting somewhere at least, 😃 

I haven't tried the autocomplete functionality, so can't comment on that.

Could you tell me how can I access it?

I've done both generating the token and logging-in twice. Cody's behaviour is still the same.

**Comment by tjdevries** [comment] 2023-10-09 16:25
If you're using nvim-cmp, it's really easy!

The docs are right here : https://github.com/sourcegraph/sg.nvim/blob/master/doc/sg.txt#L374-L396

(if they're missing something, then i'll also fix that haha!)

**Comment by Harsh97x** [comment] 2023-10-10 05:38
Implemented autocomplete, but sadly nothing works.

In fact, all the Cody's functionalities are broken for me right now. 😅 

Tried `:CodyRestart` and these errors popped up.


```Error executing Lua callback: ...harsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:52: Must pass a callback
stack traceback:
        [C]: in function 'assert'
        ...harsh/.local/share/nvim/lazy/sg.nvim/lua/sg/cody/rpc.lua:52: in function 'start'
        ...rsh/.local/share/nvim/lazy/sg.nvim/after/plugin/cody.lua:161: in function <...rsh/.local/share/nvim/lazy/sg.nvim/after/plugin/cody.lua:160>
```

**Comment by audkar** [comment] 2023-10-10 18:04
I am in an identical situation (just a Packer installation)

```
Error executing Lua callback: .../nvim/site/pack/packer/start/sg.nvim/lua/sg/cody/rpc.lua:52: Must pass a callback                   
stack traceback:
        [C]: in function 'assert'
        .../nvim/site/pack/packer/start/sg.nvim/lua/sg/cody/rpc.lua:52: in function 'start'
        ...vim/site/pack/packer/start/sg.nvim/after/plugin/cody.lua:161: in function <...vim/site/pack/packer/start/sg.nvim/after/plugin/cody.l
ua:160>
```

Arch user btw!

Are there any requirements for system libs. e.g. could there be an issue that arch neovim pkg uses `luajit 2.1.1694285958-1` (Just-in-time compiler and drop-in replacement for Lua 5.1). I have no idea how lua or neovim plugin works. But since absolutely nothing works, I would guess this is more related to some system requirement, then a bug in some specific place in the plugin's code.

**Comment by tjdevries** [comment] 2023-10-10 20:18
Ok, this one's definitely on me :upside_down_face: 

I added a callback param and forgot to update the callback style in the Restart command (... I need to add an e2e test on that, which I will later today).

Just tested with latest and I'm able to successfully restart now (it was having some weird race condition beforehand).

If you can try again (once again, sorry for the back-and-forth), that'd be great. If it's not working, please send the latest update of `checkhealth sg` cause I tried to add some more helpful debuggin info there for me.

Thanks again for your patience

**Comment by Harsh97x** [comment] 2023-10-11 05:15
`:CodyRestart` works now. Thanks for fixing that.

No errors are popping up when using Cody, but it still don't generate responses or implement specified tasks.

Here is the new `:checkhealth sg` report

```sg.nvim report ~
- OK Valid nvim version: table: 0x7fdb4ffaa8e8
- OK Found `cargo` (cargo 1.67.0 (8ecd4f20a 2023-01-10)) is executable
-     Use `:SourcegraphDownloadBinaries` to avoid building locally.
- OK Found `sg-nvim-agent`: "/home/harsh/.local/share/nvim/lazy/sg.nvim/dist/sg-nvim-agent"
- OK Found `node` (config.node_executable) is executable.
  Version: '20.5.1'
- OK Found `cody-agent`: /home/harsh/.local/share/nvim/lazy/sg.nvim/dist/cody-agent.js
- Auth strategy order: { "environment-variables", "nvim", "cody-app" }
- OK   Authentication setup correctly ("nvim")
- OK     endpoint set to: https://sourcegraph.com
- OK sg.nvim is ready to run
```

**Comment by tjdevries** [comment] 2023-10-11 17:24
So... this may actually have been the problem (found here: https://github.com/sourcegraph/sg.nvim/issues/156)

I just pushed a new release and am desperately hopeful that it will work haha. (I will also see about getting some better error messages here in case it wasn't the solve...)

You could try latest version (and make sure you have latest binaries with :SourcegraphDownloadBinaries) and... hopefully? something will work for you haha. That was definitely an unexpected issue for me

**Comment by audkar** [comment] 2023-10-11 17:30
I can confirm. Everything started working :tada: 

> Arch user btw!
> 
> Are there any requirements for system libs?

These damn Arch users with newer system libs :D

**Comment by tjdevries** [comment] 2023-10-11 18:17
me to the arch users:

![image](https://media0.giphy.com/media/3o84szW0PrWZyUv0mA/giphy.gif?cid=ecf05e47o230z1b6grpkn64ipdf6dkkcd3002x4g4qwnwnnv&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by Harsh97x** [comment] 2023-10-12 03:18
Let's fricking go!

Everything works perfectly after updating.

Thanks for your patience and persistence. 🙇🏻

**Closed** 2023-10-12 03:19 UTC
